[package]
name = "paperboids"
version = "0.1.0"
authors = ["quote <quote@dust.io>"]

[dependencies]
cgmath = "*"
glfw = "*"
time = "*"
gl = "*"
image = "*"
rand = "*"
tobj = "*"
png = "*"
byteorder = "*"
